### ISSUE TITLE
How to increase the reosolution?

### ISSUE THREAD

**Issue by domgraziano** [ACMILabs/bowiepixel#1]
Great project, however I'm finding hard to understand how to increase the resolution in pixel of the image in the background. Would be good spend a bit more to explain in the documentation or in the comments how to do it. Suppose I would like to show an image with an higher resolution 128 for example, what are the other parameters that should change in the code (apart from PIXEL_IMAGE_DIMENSIONS and the image iteself) ?

**Comment by andrewserong** [comment]
Hi @domgraziano,

The two things to update are the `PIXEL_IMAGE_DIMENSIONS` variable, and then the CSS to style each 'pixel' and set its size. You'll just want to update the `width` attribute of `#pixelContainer img` in `bowiepixel.css`. The calculation to use for the width is **100** / PIXEL_IMAGE_DIMENSIONS. So if you were using a 32 x 32 image, you'd set the width to attribute to `width: 3.125%`.

Also, unfortunately due to changes in Instagram's terms of service, this web app will likely no longer comply with their API policies, so if you plan on using this code for a project, you may wish to look into Flickr or another service to get your images.
